---
- name: install docker
  hosts: dev
  become: true
  
  tasks:
  - name: ensure repository key is installed
    apt_key:
     url: https://download.docker.com/linux/ubuntu/gpg
     state: present

  - name: ensure docker registry is available
    apt_repository: repo='deb https://download.docker.com/linux/ubuntu bionic stable' state=present

  - name: ensure docker and dependencies are installed
    apt: name=docker-ce update_cache=yes

   # Uncomment the following to enable insecure registries with Docker
    #- name: ensure docker can use insecure registries in 10.11.0.0/16
    #lineinfile: "dest=/etc/default/docker regexp=^DOCKER_OPTS line=DOCKER_OPTS='--insecure-registry 10.11.0.0/16'"

  - service: name=docker state=restarted
  
  - name: Pull default Docker image
    docker_image:
     name: "sreekanth143/sreekanthnarahari:first"
     source: pull
     
  - name: start the container
    docker_container:
      name: sreekanth
      image: "sreekanth143/sreekanthnarahari:first"
      state: started
      published_ports:
        - 0.0.0.0:9010:9010
      
